apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello1
  namespace: serverless
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/window: 60s
    spec:
      containers:
      - env:
        - name: USER_NAME
          value: LAZYken
        image: docker.io/lazyken/sampleapp:v1@sha256:6019b3e85615fdb77256660f0de71f42a7b2c83ba5219612eddb8a3db9199cba
        ports:
        - containerPort: 5000
      nodeSelector:
        kubernetes.io/hostname: edge-node
