apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/window: 100s
        autoscaling.knative.dev/min-scale: '1'
        autoscaling.knative.dev/max-scale: '1'
    spec:
      containers:
      - image: docker.io/lazyken/sampleapp:v1
        ports:
        - containerPort: 5000
        env:
          - name: USER_NAME
            value: 'LAZYken'
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
      nodeSelector:
        kubernetes.io/hostname: edge-node