apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: measure-web
  namespace: serverless
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/window: 100s
        autoscaling.knative.dev/min-scale: '1'
        autoscaling.knative.dev/max-scale: '1'
    spec:
      containers:
      - image: docker.io/lazyken/measure-app:v1@sha256:a50a275cc158657bae4a86de629dbc9efc6b9ed4d238263d0f6cdafd7363a53c
        ports:
        - containerPort: 5000
        env:
            - name: DB_HOST
              value: '192.168.17.162'
            - name: DB_USER
              value: 'thai'
            - name: DB_PASSWORD
              value: 'PQThai29112003'
      nodeSelector:
        kubernetes.io/hostname: cloud-node