apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: measure-web
  namespace: serverless
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/window: 100s
        autoscaling.knative.dev/min-scale: '1'
        autoscaling.knative.dev/max-scale: '1'
    spec:
      containers:
      - image: docker.io/lazyken/measure-app:v2@sha256:b391d7ef71ec0812c05fd2d06973103ee95b30c842c4ce4d375f55b36ca19a4a
        ports:
        - containerPort: 5000
        env:
            - name: DB_HOST
              value: '192.168.17.162'
            - name: DB_USER
              value: 'thai'
            - name: DB_PASSWORD
              value: 'PQThai29112003'
      nodeSelector:
        kubernetes.io/hostname: cloud-node
